name: Setup Script Testing
on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Download Setup script
        uses: actions/checkout@v2

      - name: Execute Setup Script
        run: ./setup.sh

      - name: Test Akebi
        run: akebi